{{- if .Values.client.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-client
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf3-client
      app.kubernetes.io/instance: {{.Release.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf3-client
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - iperf3
      containers:
        - name: iperf3
          image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}
          command:
            - bash
            - -c
            - |
              while true; do sleep 1; done
      restartPolicy: Always
status: {}
{{- end }}
