{{- if .Values.client.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-client
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf3-client
      app.kubernetes.io/instance: {{.Release.Name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf3-client
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: NotIn
                values:
                - iperf3
            topologyKey: topology.kubernetes.io/zone
      containers:
        - name: iperf3
          image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}
          command:
            - bash
            - -c
            - |
              while true; do sleep 1; done
      restartPolicy: Always
status: {}
{{- end }}
